### ISSUE TITLE
Register addons failed on latest blender version 4.4.0

### ISSUE THREAD

**Issue by jeremy-bepoix** [ynput/ayon-blender#106]
### Is there an existing issue for this?

- [x] I have searched the existing issues and added correct labels.

## Current Behavior
In the latest version of blender (4.4.0), addons don't register, or no longer do. Sinc working on blender 4.2.8

## 
erro log : 
```
Traceback (most recent call last):
  File "C:\Users\jebepoix\AppData\Local\Ynput\AYON\addons\blender_0.2.7\ayon_blender\api\lib.py", line 141, in append_user_scripts
    load_scripts(user_scripts.split(os.pathsep))
  File "C:\Users\jebepoix\AppData\Local\Ynput\AYON\addons\blender_0.2.7\ayon_blender\api\lib.py", line 93, in load_scripts
    test_register(mod)
  File "C:\Users\jebepoix\AppData\Local\Ynput\AYON\addons\blender_0.2.7\ayon_blender\api\lib.py", line 72, in test_register
    bpy.utils._global_loaded_modules.append(mod.__name__)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'bpy.utils' has no attribute '_global_loaded_modules'
```

## Solution
i can see on latest update on scripts/modules/bpy/utils/__init__.py
https://projects.blender.org/blender/blender/commit/02a74e0fa969ce223e62e6150c1464de0c805ff0

that `_global_loaded_modules` no longer support and supposed replace by : `_registered_module_names`.
Or or it has been depreciated and removed ?! (I didn't check more)

## Tested
With simple try except and working on both blender 4.2.8 & blender 4.4.0 : 

Replace : 
`unregister_module_call` > `_unregister_module_call`
`register_module_call` > `_register_module_call`

```python
    def test_register(mod):
        if mod:
            _register_module_call(mod)
            try : 
                bpy.utils._registered_module_names.append(mod.__name__)
            except:
                bpy.utils._global_loaded_modules.append(mod.__name__)
```

now i can run both

### Version
Ayon : 1.4.2+202409231943

### What platform were you running when you found the bug?
Windows 10
Blender 4.2.8
Blender 4.4.0

### Relevant log output:

```shell

```

**Comment by BigRoy** [comment]
Please see:
- https://github.com/ynput/ayon-blender/pull/103
- https://github.com/ynput/ayon-blender/pull/102

With both I have tested 4.4 just fine.

**Comment by jeremy-bepoix** [comment]
Oh, I hadn't noticed..sorry for the noise.
thanks
