### PR TITLE
Extract FBX or layout: Avoid IndexError if object name does not contain `:`

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Extract FBX or layout: Avoid IndexError if object name does not contain `:`

## Additional review information

Fix https://github.com/ynput/ayon-blender/issues/45

## Testing notes:

This may only work with Blender versions 4.1 and lower, see: https://github.com/ynput/ayon-blender/issues/45#issuecomment-2694628505 and may need _additional_ fixes for Blender 4.1+

1. Load some rig and animate it
2. Create Animation publish instance
3. Enable FBX optional flag for extracting FBX too
4. Publish should succeed

### CODE REVIEW

**Review by moonyuet — APPROVED** [review]
Code looks good to me. Didn't perform any test. @LiborBatek can you test it before the merge?

**Review by LiborBatek — DISMISSED** [review]
I have tested in newer ```blender 4.4.x``` and also in ```blender 4.1.0``` but neither of those worked for me..

I m getting errors while trying to publish ```animation``` with ```Fbx``` repre enabled

```
Traceback (most recent call last):
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\pyblish\plugin.py", line 528, in __explicit_process
    runner(*args)
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\blender_0.2.9+dev\ayon_blender\plugins\publish\extract_fbx_animation.py", line 136, in process
    bpy_extras.anim_utils.bake_action_objects(
TypeError: bake_action_objects() got an unexpected keyword argument 'do_object'
```

Also enclosing full JSON:
[B3d_publish-report-250417-14-52.json.txt](https://github.com/user-attachments/files/19794464/B3d_publish-report-250417-14-52.json.txt)

**Comment by moonyuet** [comment]
> I have tested in newer `blender 4.4.x` and also in `blender 4.1.0` but neither of those worked for me..
> 
> I m getting errors while trying to publish `animation` with `Fbx` repre enabled
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\lbate\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\pyblish\plugin.py", line 528, in __explicit_process
>     runner(*args)
>   File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\blender_0.2.9+dev\ayon_blender\plugins\publish\extract_fbx_animation.py", line 136, in process
>     bpy_extras.anim_utils.bake_action_objects(
> TypeError: bake_action_objects() got an unexpected keyword argument 'do_object'
> ```
> 
> Also enclosing full JSON: [B3d_publish-report-250417-14-52.json.txt](https://github.com/user-attachments/files/19794464/B3d_publish-report-250417-14-52.json.txt)

It errors out because the arguments of the `bake_action_objects` has been changed.
The fix is to add the class of `bakeOptions` to set all the FBX parameters prior to the export.
```python
        # We bake the copy of the current action for each object
        bake_options = bpy_extras.anim_utils.BakeOptions(
            only_selected=True,
            do_pose=True,
            do_object=False,
            do_visual_keying=True,
            do_constraint_clear=True,
            do_parents_clear=True,
            do_clean=False,
            do_location=True,
            do_rotation=True,
            do_scale=True,
            do_bbone=True,
            do_custom_props=True
        )
        bpy_extras.anim_utils.bake_action_objects(
            object_action_pairs,
            frames=range(int(min_frame), int(max_frame)),
            bake_options=bake_options
        )

```

**Comment by BigRoy** [comment]
Haha thanks all - the bug has been clearly commented in the PR description, and also _already solved_ as example here: https://github.com/ynput/ayon-blender/issues/45#issuecomment-2694291490

This PR currently only works with Blender 4.1 and below as the PR description states. The fact that it breaks in newer releases is unrelated to this PR.

**Review by moonyuet — COMMENTED** [review]
I tested with 4.1 but it still hits the same error on Extract Fbx
image
But when I used 3.6.5 LTS, it is published successfully. I guess it is not working for any version lower than 4.0? We need to look up which version has been changed for the API
Anyways, it is good for merging for the version lower than 4 at least.

**Comment by BigRoy** [comment]
> I tested with 4.1 but it still hits the same error on Extract Fbx image But when I used 3.6.5 LTS, it is published successfully. I guess it is not working for any version lower than 4.0? We need to look up which version has been changed for the API Anyways, it is good for merging for the version lower than 4 at least.

Correct - I mentioned 4.1 but it should be versions **below 4.1**. The change to the new API according to their API docs seems to be **since 4.1**

Anyway, you have a dedicated PR to fix that https://github.com/ynput/ayon-blender/pull/111
